-- Generated by Oracle SQL Developer Data Modeler 19.4.0.350.1424
--   at:        2023-02-15 11:56:22 EST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g



CREATE TABLE categorie (
    id_categorie    NUMBER NOT NULL,
    type_categorie  VARCHAR2(30) NOT NULL
);

ALTER TABLE categorie ADD CONSTRAINT categorie_pk PRIMARY KEY ( id_categorie );

CREATE TABLE commande (
    id_commande                 NUMBER NOT NULL,
    adresse                     VARCHAR2(30) NOT NULL,
    date_commande               DATE NOT NULL,
    statut_envoye               CHAR(1) NOT NULL,
    utilisateur_id_utilisateur  NUMBER NOT NULL,
    paiement_id_paiement        NUMBER NOT NULL
);

ALTER TABLE commande ADD CONSTRAINT commande_pk PRIMARY KEY ( id_commande );

CREATE TABLE item__commande (
    id_item_comm          NUMBER NOT NULL,
    quantite              NUMBER NOT NULL,
    prix                  NUMBER NOT NULL,
    commande_id_commande  NUMBER NOT NULL
);

ALTER TABLE item__commande ADD CONSTRAINT item__commande_pk PRIMARY KEY ( id_item_comm );

CREATE TABLE paiement (
    id_paiement                     NUMBER NOT NULL,
    frais_paimt                     NUMBER NOT NULL,
    type_paiement_id_type_paiement  NUMBER NOT NULL
);

CREATE UNIQUE INDEX paiement__idx ON
    paiement (
        type_paiement_id_type_paiement
    ASC );

ALTER TABLE paiement ADD CONSTRAINT paiement_pk PRIMARY KEY ( id_paiement );

CREATE TABLE produit (
    id_produit                   NUMBER NOT NULL,
    nom                          VARCHAR2(30) NOT NULL,
    description                  VARCHAR2(50),
    prix_suggere                 NUMBER,
    prix_fixe                    NUMBER NOT NULL,
    url_catalog                  VARCHAR2(30),
    inventaire                   VARCHAR2(30) NOT NULL,
    quantite                     NUMBER NOT NULL,
    item__commande_id_item_comm  NUMBER,
    categorie_id_categorie       NUMBER NOT NULL
);

ALTER TABLE produit ADD CONSTRAINT produit_pk PRIMARY KEY ( id_produit );

CREATE TABLE table_session (
    id_table_session            NUMBER NOT NULL,
    jettons                     VARCHAR2(30) NOT NULL,
    utilisateur_id_utilisateur  NUMBER NOT NULL
);

CREATE UNIQUE INDEX table_session__idx ON
    table_session (
        utilisateur_id_utilisateur
    ASC );

ALTER TABLE table_session ADD CONSTRAINT table_session_pk PRIMARY KEY ( id_table_session );

CREATE TABLE type_paiement (
    id_type_paiement      NUMBER NOT NULL,
    modalite_paimt        VARCHAR2(30) NOT NULL,
    fournisseur_paimt     VARCHAR2(30) NOT NULL,
    paiement_id_paiement  NUMBER NOT NULL
);

CREATE UNIQUE INDEX type_paiement__idx ON
    type_paiement (
        paiement_id_paiement
    ASC );

ALTER TABLE type_paiement ADD CONSTRAINT type_paiement_pk PRIMARY KEY ( id_type_paiement );

CREATE TABLE type_utilisateure (
    id_type_utilisateur  NUMBER NOT NULL,
    droit                VARCHAR2(30) NOT NULL
);

ALTER TABLE type_utilisateure ADD CONSTRAINT type_utilisateure_pk PRIMARY KEY ( id_type_utilisateur );

CREATE TABLE utilisateur (
    id_utilisateur                         NUMBER NOT NULL,
    nom                                    VARCHAR2(30) NOT NULL,
    prenom                                 VARCHAR2(30) NOT NULL,
    email                                  VARCHAR2(30) NOT NULL,
    mot_de_passe                           VARCHAR2(30) NOT NULL, 
 
    type_utilisateure_id_type_utilisateur  NUMBER NOT NULL,
    table_session_id_table_session         NUMBER NOT NULL
);

CREATE UNIQUE INDEX utilisateur__idx ON
    utilisateur (
        table_session_id_table_session
    ASC );

ALTER TABLE utilisateur ADD CONSTRAINT utilisateur_pk PRIMARY KEY ( id_utilisateur );

ALTER TABLE commande
    ADD CONSTRAINT commande_paiement_fk FOREIGN KEY ( paiement_id_paiement )
        REFERENCES paiement ( id_paiement );

ALTER TABLE commande
    ADD CONSTRAINT commande_utilisateur_fk FOREIGN KEY ( utilisateur_id_utilisateur )
        REFERENCES utilisateur ( id_utilisateur );

ALTER TABLE item__commande
    ADD CONSTRAINT item__commande_commande_fk FOREIGN KEY ( commande_id_commande )
        REFERENCES commande ( id_commande );

ALTER TABLE paiement
    ADD CONSTRAINT paiement_type_paiement_fk FOREIGN KEY ( type_paiement_id_type_paiement )
        REFERENCES type_paiement ( id_type_paiement );

ALTER TABLE produit
    ADD CONSTRAINT produit_categorie_fk FOREIGN KEY ( categorie_id_categorie )
        REFERENCES categorie ( id_categorie );

ALTER TABLE produit
    ADD CONSTRAINT produit_item__commande_fk FOREIGN KEY ( item__commande_id_item_comm )
        REFERENCES item__commande ( id_item_comm );

ALTER TABLE table_session
    ADD CONSTRAINT table_session_utilisateur_fk FOREIGN KEY ( utilisateur_id_utilisateur )
        REFERENCES utilisateur ( id_utilisateur );

ALTER TABLE type_paiement
    ADD CONSTRAINT type_paiement_paiement_fk FOREIGN KEY ( paiement_id_paiement )
        REFERENCES paiement ( id_paiement );

ALTER TABLE utilisateur
    ADD CONSTRAINT utilisateur_table_session_fk FOREIGN KEY ( table_session_id_table_session )
        REFERENCES table_session ( id_table_session );


ALTER TABLE utilisateur
    ADD CONSTRAINT utilisateur_type_utilisateure_fk FOREIGN KEY ( type_utilisateure_id_type_utilisateur )
        REFERENCES type_utilisateure ( id_type_utilisateur );



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                             9
-- CREATE INDEX                             4
-- ALTER TABLE                             19
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          0
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0
