export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}
import Navbar from '../components/HeaderBar'
import Footer from '../components/Footer'

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Navbar />
        <body>{children}</body>
      <Footer />
    </html>
  )
}
